# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-9dc4fe0f-758d-4019-a505-36fa76da0709";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-9dc4fe0f-758d-4019-a505-36fa76da0709".device =
    "/dev/disk/by-uuid/9dc4fe0f-758d-4019-a505-36fa76da0709";
  boot.initrd.luks.devices."luks-fb9a1344-76d4-4917-b96b-99b04884959a".device =
    "/dev/disk/by-uuid/fb9a1344-76d4-4917-b96b-99b04884959a";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-9dc4fe0f-758d-4019-a505-36fa76da0709";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-9dc4fe0f-758d-4019-a505-36fa76da0709";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/590B-EA24";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-fb9a1344-76d4-4917-b96b-99b04884959a"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
