"$schema" = "https://starship.rs/config-schema.json"

format = "$character"
add_newline = false
palette = "srcery"

[palettes.srcery]
color_green = "#519f50"
color_red = "#ef2f27"

[character]
disabled = false
success_symbol = "[](bold fg:color_green)"
error_symbol = "[](bold fg:color_red)"
